export enum AdminRoles{
    RETAIL_SUPER_ADMIN = "RETAIL_SUPER_ADMIN",
    RETAIL_SUPER_ADMIN_SETTING = "RETAIL_SUPER_ADMIN_SETTING",
    RETAIL_ADMIN = "RETAIL_ADMIN",
    MARKETING_ADMIN = "MARKETING_ADMIN",
    RETAIL_WH_ADMIN = "RETAIL_WH_ADMIN",
    RETAIL_CS_ADMIN = "RETAIL_CS_ADMIN",
    RETAIL_IT_ADMIN = "RETAIL_IT_ADMIN",
    RETAIL_AC_ADMIN = "RETAIL_AC_ADMIN"
  }
